#!/bin/bash
source ~/.bashrc
env
echo $PATH
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
	eval "$(pyenv init -)"
fi
pyenv install 3.6.12
pyenv global 3.6.12
python3.6 -m pip install --upgrade pip
python3.6 -m pip install tensorflow-gpu==1.13.1
